### ISSUE TITLE
无法加载出小齿轮

### ISSUE THREAD

**Issue by bolin-zhao** [ZainCheung/CSDN-helper#1]
登录了, 点开了许多博客,但是就是不能 成功显示小齿轮,是什么原因呢? 希望尽快解决

**Comment by ZainCheung** [comment]
目前已经修复了，1.1.6版本可用，可以先去油猴下载，地址：https://greasyfork.org/zh-CN/scripts/401373-csdn%E5%8D%9A%E5%AE%A2%E5%88%B7%E7%A7%AF%E5%88%86%E5%88%B7%E7%AD%89%E7%BA%A7%E5%8A%A9%E6%89%8B
另外新更新了一个马保国的评论，见：https://github.com/ZainCheung/CSDN-helper/blob/master/market/%E9%A9%AC%E4%BF%9D%E5%9B%BD.md

**Comment by bolin-zhao** [comment]
非常感谢！已经成功解决了我的问题，给你发个福利表示感谢！



---原始邮件---
发件人: "Zain"<notifications@github.com&gt;
发送时间: 2020年11月22日(周日) 晚上6:48
收件人: "ZainCheung/CSDN-helper"<CSDN-helper@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"碧水天涯"<743578561@qq.com&gt;;
主题: Re: [ZainCheung/CSDN-helper] 无法加载出小齿轮 (#1)




 
目前已经修复了，1.1.6版本可用，可以先去油猴下载，地址：https://greasyfork.org/zh-CN/scripts/401373-csdn%E5%8D%9A%E5%AE%A2%E5%88%B7%E7%A7%AF%E5%88%86%E5%88%B7%E7%AD%89%E7%BA%A7%E5%8A%A9%E6%89%8B
 另外新更新了一个马保国的评论，见：https://github.com/ZainCheung/CSDN-helper/blob/master/market/%E9%A9%AC%E4%BF%9D%E5%9B%BD.md
